flat_first.Rmd:
  path: dev/flat_first.Rmd
  state: active
  R:
  - R/chattragent_use.R
  - R/model_config.R
  tests:
  - tests/testthat/test-model_config.R
  - tests/testthat/test-chattragent_use.R
  vignettes: vignettes/get-started.Rmd
  inflate:
    flat_file: dev/flat_first.Rmd
    vignette_name: Get started
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
