# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' chattragent_use
#' 
#' chattr agent setting
#' @param agent the agent name in the dataset
#' @return agent
#' 
#' @export
chattragent_use <- function(agent){
    agent <- glue::glue("agents/{agent}.txt") %>% 
      system.file(.,package = "chattragents")
    if (!file.exists(agent)){
      stop("agent is not found in the current dataset")
    } else {
      chattr::chattr_defaults(prompt = readLines(agent))
    }
    return(agent)
}
