# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' model_config
#' 
#' config models and test
#' @param provider default as openai
#' @param path the path url 
#' @param label the label of defined model
#' @param model the used model
#' @param file the saved yaml file
#' @param test_apikey the api key for model test 
#' @return yamlfile
#' 
#' @export
model_config <- function(provider = "OpenAI - Chat Completions",
                         path = "https://api.lingyiwanwu.com/v1/chat/completions",
                         label = "yi-34b-chat-0205 (01.AI)",
                         model = "yi-34b-chat-0205",
                         file = "dev/model_test.yml",
                         test_apikey
                         ){
  model_temple <- chattragents::model_temple
  model_temple$default$provider <- provider
  model_temple$default$path <- path
  model_temple$default$label <- label
  model_temple$default$model <- model
  fs::dir_create(path = basename(file))
  yaml::write_yaml(model_temple,
                   file = file)
  message("configing model,now test ...")
  Sys.setenv("OPENAI_API_KEY" = test_apikey)
  chattr::chattr_use(file)
  chattr::chattr("who are you")
  return(file)
}
